#!/usr/bin/env bash
# Fix my server with these magic 2 lines

# Ensure Apache is installed and running
apt-get update && apt-get install -y apache2

# Create a simple HTML page to be served by Apache
echo "Hello Holberton" > /var/www/html/index.html

# Restart Apache to apply the changes
service apache2 restart