#!/usr/bin/env bash
# This script ensures that Nginx is configured to listen on port 80 and is running

# Ensure that Nginx is listening on port 80
sudo sed -i 's/listen 127.0.0.1:80/listen 80 default_server;/' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
