#!/usr/bin/env bash
# Configures Nginx to have a custom 404 page

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Edit default config to use custom 404
sed -i '/server_name _;/a \\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

service nginx restart
